### ISSUE TITLE
Washed out/ Beige Images in Tensorboard using Google Colab

### ISSUE THREAD

**Issue by Zappytoes** [SJTU-Thinklab-Det/DOTA-DOAI#10]
I'm testing out this implementation on a small subset of the DOTA dataset using Google Colab. The training is going fine, but the the images in Tensorboard are washed out and beige. Could there be an issue with the images when they converted to a tfrecord, or is there some issue with Tensorboard? I'm using tensorflow-gpu = 1.13.1 & tensorboard 1.13.1

<img width="1359" alt="Screen Shot 2020-05-07 at 1 14 03 PM" src="https://user-images.githubusercontent.com/18469106/81324229-a7871a80-9064-11ea-8fb5-4fd9b57689f9.png">

**Comment by yangxue0827** [comment]
I just tested it and my tensorboard shows no problem
![image](https://user-images.githubusercontent.com/29257168/81393114-56edeb00-9152-11ea-9f2d-65a6f3a3d4ff.png)
@Zappytoes

**Comment by yangxue0827** [comment]
In addition, your second and third images are the same, both are horizontal boxes, which is problematic. It should be a rotating box and a horizontal box. I suggest you update the code again. @Zappytoes

**Comment by Zappytoes** [comment]
@yangxue0827 ok, thank you, will update.

**Comment by Zappytoes** [comment]
@yangxue0827 I was using the non-rotational in code in FPN_Tensoflow folder and the rectangular labels in labelTxt-v1.0/trainset_reclabel_Txt, so maybe that's how the gt boxes should look.

**Comment by Zappytoes** [comment]
The problem was with a bad edit i did to read_tf_record_multi_gpu.py in the image normalization step (line #80). So it was user error...
