### ISSUE TITLE
自己跑达不到所给的map

### ISSUE THREAD

**Issue by heping0228** [SJTU-Thinklab-Det/DOTA-DOAI#14]
老哥我按照那个0.70的cfgs文件跑，达不到所说的0.70，只有0.5多，这是怎么回事，，

**Comment by yangxue0827** [comment]
这个不清楚，这些模型都是我最近跑的，所以代码上应该没啥问题。你这也没有一些具体信息，所以我也帮不上忙。 @heping0228

**Comment by heping0228** [comment]
有可能是跑的不够，我先试了２ｗ步，看了下结果，可能是ｃｖ的ｂａｔｃｈｓｉｚｅ太小的缘故，老哥跑的结果要多少轮

**Comment by yangxue0827** [comment]
2w连数据训练一轮都没有。 @heping0228

**Comment by yangxue0827** [comment]
你就按我给的默认训练完就行 @heping0228
