### ISSUE TITLE
Is it suitable for training other datasets？

### ISSUE THREAD

**Issue by zhang295498** [SJTU-Thinklab-Det/DOTA-DOAI#15]
Thx for sharing your code.
And what I want to know is that Is it suitable for training other datasets？
For eaxmple，Pascal VOC07 and MS COCO  etc. If it can do it， where should I change the code？

**Comment by yangxue0827** [comment]
of course, see [README](https://github.com/SJTU-Thinklab-Det/DOTA-DOAI/tree/master/FPN_Tensorflow)
