### ISSUE TITLE
tfrecord 10 times larger than the original training data

### ISSUE THREAD

**Issue by distillation-dcf** [SJTU-Thinklab-Det/DOTA-DOAI#18]
Hello!  I am impressed by your great work and applying the code on my own datasets. 

Following the instrucition, I transform all my DOTA-format label txt to xml, and try to generate tfrecord from all the xml. After finishing convert_data_to_tfrecord.py, I get a tfrecord about 300G( original training images and labels are only 20G+).

 Is there anything wrong? Is it possible to read training images and original labels online during training?

**Comment by yangxue0827** [comment]
Of course you can, you need rewrite next_batch function, and use placeholder form. Here is a [example](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/train_with_placeholder.py).
