### ISSUE TITLE
getting error while trying to run setup.py

### ISSUE THREAD

**Issue by omeryasar** [SJTU-Thinklab-Det/DOTA-DOAI#23]
Hi,
My working environment: windows 10, cuda 10.1, python 3.7, tensorflow 1.3.1 while I trying to run  'python setup.py build_ext --inplace' command I am getting an output like that; 
bbox.c(1684): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(1693): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(2374): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(2383): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(3056): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(3065): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(3692): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(3701): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(4536): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(4545): warning C4244: '=': conversion from 'npy_intp' to 'unsigned int', possible loss of data
bbox.c(9439): error C2039: 'exc_type': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9440): error C2039: 'exc_value': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9441): error C2039: 'exc_traceback': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9448): error C2039: 'exc_type': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9449): error C2039: 'exc_value': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9450): error C2039: 'exc_traceback': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9451): error C2039: 'exc_type': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9452): error C2039: 'exc_value': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9453): error C2039: 'exc_traceback': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9508): error C2039: 'exc_type': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9509): error C2039: 'exc_value': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9510): error C2039: 'exc_traceback': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9511): error C2039: 'exc_type': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9512): error C2039: 'exc_value': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9513): error C2039: 'exc_traceback': is not a member of '_ts'
C:\Users\faruk.yasar\AppData\Local\Continuum\anaconda3\include\pystate.h(212): note: see declaration of '_ts'
bbox.c(9893): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
bbox.c(9899): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2.

What should I do to fix it, thanks in advance

**Comment by yangxue0827** [comment]
use linux operating system @omeryasar
