### ISSUE TITLE
FPN_Tensorflow_Rotation的预测结果，每次都会不断追加

### ISSUE THREAD

**Issue by robin-shaun** [SJTU-Thinklab-Det/DOTA-DOAI#27]
您好，您的程序写的很棒，网络效果很好。但是在test_dota里，由于写入方式是追加的形式的，不会把之前的结果覆盖。所以如果没有删除之前的结果，之前的结果就会一直保留，导致预测框越来越多，随着网络的训练，召回率会提升，但虚警依然很多。这一点非常隐蔽，很难被发现。您可以在readme里加个提示，这样其它使用者就能注意到这点。
```
write_handle[sub_class] = open(os.path.join(save_path, 'dota_res', 'Task1_%s.txt' % sub_class), 'a+')
fw = open(txt_name, 'a+')
```

**Comment by yangxue0827** [comment]
感谢提醒，之所以用追加是方便设置断点。
