### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by gengyanlei** [SJTU-Thinklab-Det/DOTA-DOAI#31]
作者，你好，像八参数是按照一定顺序排序的，但是DOTA是起点作为对象正向(eg车辆前方左上角)的左上角，不一定是框的左上角，那么这样复杂了，请问你是如何处理的呢。

**Comment by yangxue0827** [comment]
所以需要算法进行排序，参考代码：https://github.com/yangxue0827/RotationDetection/blob/main/utils/order_points.py
