### ISSUE TITLE
SOTA榜的小问题

### ISSUE THREAD

**Issue by jedibobo** [SJTU-Thinklab-Det/DOTA-DOAI#37]
<img width="557" alt="36de9c414a6e0f47fc3ec1cab3459d7" src="https://user-images.githubusercontent.com/44748473/146641302-5b7098b2-08a0-4725-8c73-f97f26fae7f3.png">
<img width="545" alt="daba947548b4fd67387efac7b5ddb6a" src="https://user-images.githubusercontent.com/44748473/146641307-ee2795a7-d2ed-4711-abd2-5c60c9ae4b3c.png">
ｅｍｍ这个S2ANet+DAL的效果还不如S2ANet，我看后面跟的repo貌似不是基于S2ANet做的，只是在论文里面提到有这个结果。

**Comment by johnson-magic** [comment]
我已收到，。

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/146641857-17620eb5-04be-4fd4-9679-769991268381.png)
他并没有使用S2ANet最好的配置跑的，所以不能单纯这么比较，他的arxiv版本给了添加DAL前后基于S2ANet的性能变化。
@jedibobo
