### ISSUE TITLE
Epoch control?

### ISSUE THREAD

**Issue by Zappytoes** [SJTU-Thinklab-Det/DOTA-DOAI#4]
Hi, thank you for posting your code. I'm looking it over to try it out on some other data and i'd like to just train over a couple epochs to make sure it is working in my environment, but i don't see an epochs option in your cfgs.py file. Where do you set the number of epochs?

Also, I think there is a small error in the read-me: I believe it should say "dataset_name" instead of "data_name"?

Thanks!

**Comment by yangxue0827** [comment]
https://github.com/SJTU-Thinklab-Det/DOTA-DOAI/blob/master/FPN_Tensorflow/libs/configs/cfgs.py#L88
@Zappytoes
