### ISSUE TITLE
Input reshape error

### ISSUE THREAD

**Issue by adamzhu1990** [SJTU-Thinklab-Det/DOTA-DOAI#7]
there is a mistake when I run FPN_Tensorflow_Rotation multi_gpu_train.py for cfgs_dota1.0_res50. detail as follow
![issue1](https://user-images.githubusercontent.com/7903514/79039909-28462880-7c17-11ea-937b-1e1dc1c49153.PNG)
how can I solve it?

**Comment by yangxue0827** [comment]
you can add my wechat account: yangxue-0826
